version: '3.9'

networks:
  c4unetwork:
      driver: bridge

services:
  web:
    build: .
    command: gunicorn main:app --timeout 1000 --bind 0.0.0.0:6969
    volumes:
      - ./cllg/data.csv:/usr/src/app/cllg/data.csv:ro
    networks:
      - c4unetwork
    restart:
      "unless-stopped"