version: '3.8'

services:
  web:
    build: .
    command: gunicorn main:app --timeout 1000 --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ${PWD}/cllg/data.csv:/usr/src/app/cllg/data.csv